export const AGE_VALUE_INCREMENT = "AGE_VALUE_INCREMENT";
export const AGE_VALUE_DECREMENT = "AGE_VALUE_DECREMENT";
export const AGE_VALUE_DELETE = "AGE_VALUE_DELETE";
export const LOADING = "LOADING";
